#!/usr/bin/perl -w

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks qw(:all);


my @templates = qw(
    /etc/postfix/main.cf
    /etc/postfix/master.cf
    /etc/postfix/transport
    /etc/postfix/vmailbox
    /etc/amavisd/amavisd.conf
);

#
# UPDATE event
#

event_templates('nethserver-mail-dev-update', @templates);

event_actions('nethserver-mail-dev-update',
	      'nethserver-mail-postmap-update' => '30',
	      );

event_services('nethserver-mail-dev-update',
	       'amavisd' => 'restart',
	       'postfix' => 'restart');
